apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  namespace: purchase-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: inventory-app
          image: {{ .Values.app.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.app.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secret
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  namespace: purchase-app
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}