apiVersion: apps/v1
kind: Deployment
metadata:
  name: artemis-broker
  namespace: purchase-app
  labels:
    {{- include "artemis.selectorLabels" . | nindent 8 }}
spec:
  replicas: {{ .Values.artemis.replicas }}
  selector:
    matchLabels:
      {{- include "artemis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "artemis.selectorLabels" . | nindent 8 }}
        {{- include "artemis.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.artemis.image.repository }}:{{ .Values.artemis.image.tag }}"
        imagePullPolicy: {{ .Values.artemis.image.pullPolicy }}
        env:
        - name: ARTEMIS_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "artemis.secretName" . }}
              key: username
        - name: ARTEMIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "artemis.secretName" . }}
              key: password
        - name: ANONYMOUS_LOGIN
          valueFrom:
            configMapKeyRef:
              name: {{ include "artemis.configmapName" . }}
              key: anonymous-login
        ports:
        - containerPort: {{ .Values.artemis.ports.core }}
        - containerPort: {{ .Values.artemis.ports.web }}
        {{- if .Values.artemis.storage.enabled }}
        volumeMounts:
        - name: artemis-data
          mountPath: {{ .Values.artemis.storage.mountPath }}
        {{- end }}
        {{- if .Values.artemis.livenessProbe.enabled }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.artemis.livenessProbe.port }}
          initialDelaySeconds: {{ .Values.artemis.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.artemis.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.artemis.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.artemis.livenessProbe.failureThreshold }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if .Values.artemis.storage.enabled }}
      volumes:
      - name: artemis-data
        persistentVolumeClaim:
          claimName: {{ include "artemis.pvcName" . }}
      {{- end }}