apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend-chart.fullname" . }}
  namespace: purchase-app
  labels:
    {{- include "frontend-chart.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include ("frontend-chart.configmap") . | sha256sum }}
    debug/values: {{ .Values | toJson | sha256sum | trunc 8 }}
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "frontend-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "frontend-chart.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "frontend-chart.serviceAccountName" . }}
      containers:
        - name: {{ include "frontend-chart.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: FOO
              value: {{ .Values.foo | quote }}
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/js/config.js
              subPath: config.js
      volumes:
        - name: config
          configMap:
            name: {{ include "frontend-chart.fullname" . }}-config
