{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontend-chart.serviceAccountName" . }}
  namespace: purchase-app
  labels:
    {{- include "frontend-chart.labels" . | nindent 4 }}
{{- end }}
