apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-chart.fullname" . }}
  namespace: purchase-app
  labels:
    {{- include "frontend-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "frontend-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
