{{- if not .Values.artemis.security.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artemis.secretName" . }}
  namespace: purchase-app
  labels:
    {{- include "artemis.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.artemis.security.username | b64enc | quote }}
  password: {{ .Values.artemis.security.password | b64enc | quote }}
{{- end }}