apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.keycloak.adminUser }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.adminPassword }}