apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      containers:
      - name: promtail
        image: grafana/promtail:2.9.2
        args:
        - -config.file=/etc/promtail/promtail.yaml
        - -config.expand-env=true  # Add this line
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 9080
          name: http
        volumeMounts:
          - name: config
            mountPath: /etc/promtail/promtail.yaml  # Fixed path
            subPath: promtail.yaml
          - name: positions
            mountPath: /positions
          - name: varlogpods
            mountPath: /var/log/pods
            readOnly: true
          - name: varlog
            mountPath: /var/log
            readOnly: true
          - name: audit
            mountPath: /var/log/kubernetes/audit
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: positions
          hostPath:
            path: /var/lib/promtail
            type: DirectoryOrCreate
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlog
          hostPath:
            path: /var/log
        - name: audit
          hostPath:
            path: /var/log/kubernetes/audit