replicaCount: 1
environment: "development" # Added

image:
  repository: localhost:5000/nginx-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

serviceAccount:
  create: true

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts: []
  tls: []
  host: frontend.local

keycloak:
  url: "https://keycloak.local"
  realm: "purchase-service-realm"
  clientId: "web-frontend-client"

api:
  purchases: "purchase-api/purchases"
  inventory: "inventory-api/inventory"

# Optional: if you want to keep the foo environment variable
foo: "default-value"
