# ../charts/test-chart/templates/print-values.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: debug-values
data:
  merged-values.yaml: |
{{ toYaml .Values | indent 4 }}
  # app-project.txt: |
  #   {{ .Values.Name }}-{{ .Values.project }}
