{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx 
    cert-manager.io/cluster-issuer: my-ca-issuer #must match issuer name
    nginx.ingress.kubernetes.io/ssl-redirect: "true" #redirect http to https
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - keycloak.local
    secretName: keycloak-secret #this must match what is in certificate
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: {{ $.Values.keycloak.service.port | default 8080 }}
          {{- end }}
{{- end }}
