apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.keycloak.serviceType }}
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080