gitlabUrl: https://gitlab.rlp.net
runnerToken: "glrt-0Ya8iHlZAcFVLKfX1-nr9G86MQpwOjEybjAKdDozCnU6anppFA.01.1e1i3b4bn"

rbac:
  create: false
serviceAccount:
  create: false
  name: gitlab-runner
runners:
  privileged: true
  kubernetes:
    hostNetwork: true
    serviceAccount: gitlab-runner
  config: |
    [[runners]]
      name = "gitlab-runner-hostnet"
      executor = "kubernetes"
      [runners.kubernetes]
        image = "alpine:latest"
        namespace = "{{.Release.Namespace}}"
        privileged = true
