apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  APP_NAME: "{{ .Values.app.name }}"
  SERVER_PORT: "{{ .Values.app.port }}"
  SPRING_PROFILES_ACTIVE: "{{ .Values.app.profile }}"
  SPRING_SECURITY_LOG_LEVEL: "{{ .Values.app.securityLogLevel }}"
  APP_QUEUE_NAME: "{{ .Values.app.queueName }}"

  DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-db:{{ .Values.database.port }}/{{ .Values.database.name }}"
  DATASOURCE_USERNAME: "{{ .Values.database.user }}"

  ARTEMIS_BROKER_URL: "tcp://{{ .Values.artemis.service }}"
  ARTEMIS_USER: "{{ .Values.artemis.user }}"

  KEYCLOAK_ISSUER_URI: "https://keycloak.local/realms/purchase-service-realm"
  KEYCLOAK_JWK_SET_URI: "http://{{ .Values.keycloak.service }}/realms/{{ .Values.keycloak.realm }}/protocol/openid-connect/certs"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  DATASOURCE_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  ARTEMIS_PASSWORD: {{ .Values.artemis.password | b64enc | quote }}
